services:
  soter: 
    image: linkaform/soter:develop
    container_name: soter
    build: 
      context: ../ 
      dockerfile: Dockerfile
      target: develop

    volumes:
      # - ./:/srv
      - ../src:/srv/src/
      - ../public:/srv/public/
      - ../cache:/srv/cache/
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: https://app.linkaform.com/api
    stdin_open: true
    command: yarn dev
    #command: /bin/bash
    tty: true
